[project]
name = "metermate"
version = "0.1.0"
description = "Your smart friend for your dumb meter"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "colorlog>=6.9.0",
    "homeassistant==2025.2.4",
    "pip>=25.1.1",
]

[dependency-groups]
dev = ["ruff>=0.11.13"]
