# MeterMate Services
# Full CRUD interface for manual utility data management

add_reading:
  name: Add Reading
  description: Add a new utility meter reading (cumulative meter reading or periodic consumption data)
  fields:
    entity_id:
      name: Entity ID
      description: The meter sensor entity to add the reading to
      required: true
      selector:
        entity:
          integration: metermate
    value:
      name: Reading Value
      description: The meter reading value or consumption amount
      required: true
      selector:
        number:
          min: 0
          step: 0.001
          mode: box
    timestamp:
      name: Reading Timestamp
      description: When the reading was taken (defaults to now)
      required: false
      selector:
        datetime:
    unit:
      name: Unit of Measurement
      description: Unit for the reading (kWh, m³, gal, etc.)
      required: false
      default: kWh
      selector:
        text:
    notes:
      name: Notes
      description: Optional notes about this reading
      required: false
      selector:
        text:
          multiline: true

update_reading:
  name: Update Reading
  description: Update an existing meter reading
  fields:
    entity_id:
      name: Entity ID
      description: The meter sensor entity
      required: true
      selector:
        entity:
          integration: metermate
    reading_id:
      name: Reading ID
      description: The ID of the reading to update
      required: true
      selector:
        text:
    value:
      name: Reading Value
      description: The updated meter reading value
      required: true
      selector:
        number:
          min: 0
          step: 0.001
          mode: box
    timestamp:
      name: Reading Timestamp
      description: When the reading was taken
      required: false
      selector:
        datetime:
    unit:
      name: Unit of Measurement
      description: Unit for the reading
      required: false
      default: kWh
      selector:
        text:
    notes:
      name: Notes
      description: Optional notes about this reading
      required: false
      selector:
        text:
          multiline: true

delete_reading:
  name: Delete Reading
  description: Delete a meter reading
  fields:
    entity_id:
      name: Entity ID
      description: The meter sensor entity
      required: true
      selector:
        entity:
          integration: metermate
    reading_id:
      name: Reading ID
      description: The ID of the reading to delete
      required: true
      selector:
        text:

get_readings:
  name: Get Readings
  description: Retrieve meter readings for a specific time period
  fields:
    entity_id:
      name: Entity ID
      description: The meter sensor entity
      required: true
      selector:
        entity:
          integration: metermate
    start_date:
      name: Start Date
      description: Start date for the query period
      required: false
      selector:
        datetime:
    end_date:
      name: End Date
      description: End date for the query period
      required: false
      selector:
        datetime:

bulk_import:
  name: Bulk Import
  description: Import multiple meter readings at once
  fields:
    entity_id:
      name: Entity ID
      description: The meter sensor entity
      required: true
      selector:
        entity:
          integration: metermate
    readings:
      name: Readings Data
      description: List of readings to import (YAML list format)
      required: true
      selector:
        object:

recalculate_statistics:
  name: Recalculate Statistics
  description: Recalculate and update Home Assistant statistics for a meter
  fields:
    entity_id:
      name: Entity ID
      description: The meter sensor entity to recalculate statistics for
      required: true
      selector:
        entity:
          integration: metermate

rebuild_history:
  name: Rebuild History
  description: Completely rebuild historical data for a meter, with option to wipe all existing data first
  fields:
    entity_id:
      name: Entity ID
      description: The meter sensor entity to rebuild history for
      required: true
      selector:
        entity:
          integration: metermate
    complete_wipe:
      name: Complete Wipe
      description: If enabled, completely wipes all existing data (states, statistics) before rebuilding. If disabled, performs incremental cleanup.
      required: false
      default: true
      selector:
        boolean:

# Enhanced Services for Meter Reading Management

add_meter_reading:
  name: Add Meter Reading
  description: Add a meter reading and automatically calculate consumption from the previous reading
  fields:
    entity_id:
      name: Entity ID
      description: The meter sensor entity to add the reading to
      required: true
      selector:
        entity:
          integration: metermate
    meter_reading:
      name: Meter Reading
      description: The actual meter reading value (cumulative)
      required: true
      selector:
        number:
          min: 0
          step: 0.001
          mode: box
    timestamp:
      name: Reading Timestamp
      description: When the reading was taken (defaults to now)
      required: false
      selector:
        datetime:
    unit:
      name: Unit of Measurement
      description: Unit for the reading (kWh, m³, gal, etc.)
      required: false
      default: kWh
      selector:
        text:
    notes:
      name: Notes
      description: Optional notes about this reading (e.g., bill number)
      required: false
      selector:
        text:

add_consumption_period:
  name: Add Consumption Period
  description: Add consumption data for a period and automatically calculate the ending meter reading
  fields:
    entity_id:
      name: Entity ID
      description: The meter sensor entity to add the consumption to
      required: true
      selector:
        entity:
          integration: metermate
    consumption:
      name: Consumption Amount
      description: The amount consumed during the period
      required: true
      selector:
        number:
          min: 0
          step: 0.001
          mode: box
    period_start:
      name: Period Start
      description: Start date and time of the consumption period
      required: true
      selector:
        datetime:
    period_end:
      name: Period End
      description: End date and time of the consumption period
      required: true
      selector:
        datetime:
    unit:
      name: Unit of Measurement
      description: Unit for the consumption (kWh, m³, gal, etc.)
      required: false
      default: kWh
      selector:
        text:
    notes:
      name: Notes
      description: Optional notes about this period (e.g., bill number)
      required: false
      selector:
        text:
