add_reading:
  name: Add Reading
  description: Add a new meter reading to a MeterMate sensor.
  fields:
    entity_id:
      name: Entity
      description: The MeterMate sensor entity to add the reading to.
      required: true
      example: sensor.grid_electricity
      selector:
        entity:
          domain: sensor
          integration: metermate
    value:
      name: Reading Value
      description: The meter reading value.
      required: true
      example: 15650
      selector:
        number:
          min: 0
          step: 0.001
          mode: box
    mode:
      name: Reading Mode
      description: How to interpret the reading value.
      required: false
      default: cumulative
      example: cumulative
      selector:
        select:
          options:
            - value: cumulative
              label: Cumulative (total meter reading)
            - value: periodic
              label: Periodic (consumption for a period)
    timestamp:
      name: Timestamp
      description: When the reading was taken (for cumulative mode only).
      required: false
      example: "2025-01-15 10:30:00"
      selector:
        datetime:
    start_date:
      name: Start Date
      description: Start date for the consumption period (for periodic mode only).
      required: false
      example: "2025-01-01"
      selector:
        date:
    end_date:
      name: End Date
      description: End date for the consumption period (for periodic mode only).
      required: false
      example: "2025-01-31"
      selector:
        date:
